
import {shrek} from "../constants.js";
let names = [
    "Albert",
    "Léonard",
    "Marie",
    "Winston",
    "Frida",
    "Salvador",
    "Sherlock",
    "Hermione",
    "Luke",
    "Elsa",
    "Pablo",
    "Napoleon",
    "Julius",
    "Anaïs",
    "Jean-Paul",
    "Billie",
    "Audrey",
    "Gandhi",
    "Charles",
    "Cleopatra",
    "Batman",
    "Scarlett",
    "Aragorn",
    "Indiana",
    "Katniss",
    "Zorro",
    "Zelda",
    "Albertine",
    "Shrek",
    "Simba",
    "Harry",
    "Simba",
    "Anakin",
    "Daenerys",
    "Neo",
    "Buffy",
    "Luffy",
    "Thor",
    "Maya",
    "Michelangelo",
    "Odysseus",
    "Lara",
    "Spock",
    "Madeline",
    "Jules",
    "Marie-Antoinette",
    "Romain",
    "Yoda",
    "Zelda",
    "Tony"];
let lastNames = [
    "Einstein",
    "de Vinci",
    "Curie",
    "Churchill",
    "Kahlo",
    "Dalí",
    "Holmes",
    "Granger",
    "Skywalker",
    "de Frozen",
    "Picasso",
    "Bonaparte",
    "Caesar",
    "Nin",
    "Sartre",
    "Holiday",
    "Hepburn",
    "Gandhi",
    "Darwin",
    "Cleopatra",
    "Wayne",
    "O'Hara",
    "Baggins",
    "Jones",
    "Everdeen",
    "Vega",
    "Fitzgerald",
    "Proust",
    "Gray",
    "Simba",
    "Potter",
    "Skywalker",
    "Targaryen",
    "Reeves",
    "Summers",
    "D",
    "Thor",
    "Angelou",
    "Shrek",
    "Ulysses",
    "Croft",
    "Spock",
    "Chaucer",
    "Verne",
    "Antoinette",
    "Gary",
    "Yoda",
    "Zelda",
    "Stark"];


function User(){
    this.name = names[Math.floor(Math.random() * names.length)];
    this.lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
    this.age = Math.floor(Math.random() * 500);
}

let users = Array.from(new Array(50), x => new User());

console.table(users);

console.log(shrek);